project/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    # READ : list_view
    path("", read_all_function, name="read_all"),
    # READ : detail_view
    path("blog/<int:id>", read_one_function, name="read_one"),
    # Create
    path("new/", new_function, name="new"),
    path("blog/create/", create_function, name="create"),
    # Update
    path("blog/edit/<int:id>", edit_function, name="edit"),
    path("blog/update/<int:id>", update_function, name="update"),
    # DELETE
    path("blog/delete/<int:id>", delete_function, name="delete"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
]

project/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('signup/', signup_function, name="signup"),
    path('signin/', signin_function, name="signin"),
    path('signout/', signout_function, name="signout"),
]

project/blog/models.py
from django.db import models

class Blog(models.Model):
    writer = models.ForeignKey('user.CustomUser', related_name='blog_writer', on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:50]

project/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, username, password, **kwargs):
        user = self.model(username=username, **kwargs)
        user.set_password(password)
        user.save()

    def create_normaluser(self, username, password, **kwargs):
        self.create_user(username, password, **kwargs)

    def create_superuser(self, username, password, **kwargs):
        kwargs.setdefault("is_superuser", True)
        self.create_user(username, password, **kwargs)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'username'

    username = models.CharField(unique=True, max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CustomUserManager()

    @property
    def is_staff(self):
        return self.is_superuser


project/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

project/user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

# 회원가입 폼
class CustomUserSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username']

# 로그인(인증) 폼
class CustomUserSigninForm(AuthenticationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username']

project/blog/views.py
from django.http import QueryDict
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog
from .forms import BlogForm

# READ
def read_all_function(request):
    blogs = Blog.objects.all()
    return render(request, "home.html", {"blogs":blogs})

# READ
def read_one_function(request, id):
    blog = get_object_or_404(Blog, pk=id)
    return render(request, "detail.html", {"blog":blog})

# CREATE 를 위한 리소스 띄우기
def new_function(request):
    return render(request, "new.html")

# CREATE
def create_function(request):
    form = BlogForm(request.POST)
    if form.is_valid():
        create_blog = form.save(commit=False)
        create_blog.writer = request.user # 안쓰면 개고생한다
        create_blog.save()
        return redirect('blog:read_one', create_blog.id)
    return render(request, "new.html", {'form':form})

# UPDATE 를 위한 리소스 띄우기
def edit_function(request, id):
    edit_blog = get_object_or_404(Blog, pk=id)
    return render(request, "edit.html", {"edit_blog":edit_blog})

# UPDATE
def update_function(request, id):
    update_blog_old = get_object_or_404(Blog, pk=id)
    form = BlogForm(request.POST, instance=update_blog_old)

    if request.method == "POST":
        # make_error = QueryDict.copy(request.POST)
        # make_error["title"] = ""
        # form = BlogForm(make_error, instance=update_blog_old)
        if form.is_valid():
            update_blog_new = form.save(commit=False)
            update_blog_new.save()
            return redirect("blog:read_one", update_blog_new.id)

    return render(request, "new.html", {"form":form, "update_blog_old":update_blog_old})

# DELETE
def delete_function(request, id):
    delete_blog = get_object_or_404(Blog, pk=id)
    delete_blog.delete()
    return redirect("blog:read_all")

project/user/views.py
from django.http import QueryDict
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import CustomUserSignupForm, CustomUserSigninForm

# 회원가입
def signup_function(request):
    form = CustomUserSignupForm()
    if request.method == 'POST':
        form = CustomUserSignupForm(request.POST)
        # make_error = QueryDict.copy(request.POST)
        # make_error["username"] = ""
        # form = CustomUserSignupForm(make_error)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("blog:read_all")
    return render(request, "signup.html", {"form":form})

# 로그인
def signin_function(request):
    form = CustomUserSigninForm()
    if request.method == 'POST':
        form = CustomUserSigninForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect("blog:read_all")
    return render(request, "signin.html", {"form":form})

# 로그아웃
def signout_function(request):
    logout(request)
    return redirect("blog:read_all")

project/blog/templates/detail.html
<h1>detail 페이지</h1>

<p>제목: {{blog.title}}</p>
<p>글: {{blog.content}}</p>
<p>작성자: {{blog.writer}}</p>
<p>생성시기: {{blog.created_at}}</p>
<p>수정시기: {{blog.updated_at}}</p>

{% if user == blog.writer %}
<a href="{% url 'blog:read_all' %}">홈</a>
<a href="{% url 'blog:edit' blog.id %}">수정하기</a>
<a href="{% url 'blog:delete' blog.id %}">삭제</a>
{% else %}
<a href="{% url 'blog:read_all' %}">홈</a>
{% endif %}


project/blog/templates/edit.html
<h1>edit 페이지</h1>

<form method="POST" action="{% url 'blog:update' edit_blog.id %}">
    {% csrf_token %}
    <input type="text" name="title" value="{{edit_blog.title}}"/>
    <textarea name="content" id="" cols="30">{{edit_blog.content}}</textarea>
    <input type="submit" value="수정하기">
</form>

<a href="{% url 'blog:read_all' %}">홈</a>
<a href="{% url 'blog:delete' edit_blog.id%}">삭제</a>

project/blog/templates/home.html
<h1>멋사 11기 Blog 프로젝트</h1>
<br>

{% if user.is_authenticated %}
<!--로그인 상태-->
<h3>안녕하세요, {{user.username}} 님!</h3>
<a href="{% url 'user:signout' %}">로그아웃</a>
<hr>
<a href="{% url 'blog:new' %}">새 글 작성</a>
<hr>
{% for blog in blogs %}
<div>
    <a href="{% url 'blog:read_one' blog.id %}">
        <p>제목: {{blog.title}}</p>
        <p>글: {{blog.content}}</p>
        <p>작성자: {{blog.writer}}</p>
        <p>생성시기: {{blog.created_at}}</p>
        <p>수정시기: {{blog.updated_at}}</p>
        <p>요약: {{blog.summary}}</p>
        <hr>
    </a>
</div>
<br>
{% endfor %}

{% else %}
<!--로그아웃 상태-->
<a href="{% url 'user:signup' %}">회원가입</a>
<a href="{% url 'user:signin' %}">로그인</a>
<h3>로그인해야 게시판을 이용하실 수 있습니다.</h3>
{% endif %}
<hr>


project/blog/templates/new.html
<h1>new 페이지</h1>

<form method="POST" action="{% url 'blog:create' %}">
    {% csrf_token %}
    제목: <input type="text" name="title"/>
    글: <textarea name="content" id="" cols="30" rows="10"></textarea>
    <input type="submit" value="작성하기"/>
</form>

<a href="{% url 'blog:read_all' %}">홈으로 가기</a>

project/user/templates/signin.html
<h1>login 페이지</h1>

<form method="POST" action="{% url 'user:signin' %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="로그인하기" />
</form>
<a href="{% url 'blog:read_all' %}">홈으로 가기</a>

project/user/templates/signup.html
<h1>signup 페이지</h1>

<form method="POST" action="{% url 'user:signup' %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="회원가입하기" />
</form>
<a href="{% url 'blog:read_all' %}">홈으로 가기</a>